services:
  db:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
